name: ${project.name}
provides: []
version: ${project.version}
description: A plugin that adds some useful features to tridents.
authors: [mfnalex, JEFF Media GbR]
contributors: [Krakenied]
website: https://www.mfnalex.de

main: ${project.groupId}.${project.artifactId}.${project.name}
load: STARTUP
depend: []
softdepend: []
api-version: 1.18
libraries: []

commands:
  ${project.artifactId}:
    description: Reloads ${project.name}.
    permission: ${project.artifactId}.reload
    usage: /<command>

permissions:
  ${project.artifactId}.*:
    default: op
    description: Players with this permission will be able to use all of the plugin features.
    children:
      ${project.artifactId}.savevoid: true
      ${project.artifactId}.reload: true
  ${project.artifactId}.savevoid:
    default: true
    description: Players with this permission will not lose their loyalty-enchanted tridents after throwing them into the void.
  ${project.artifactId}.reload:
    default: false
    description: Players with this permission will be able to reload the plugin by using /${project.artifactId} command.